name       : urw-core35-fonts
version    : 28082015
release    : 1
source     :
    - http://git.ghostscript.com/?p=urw-core35-fonts.git;a=snapshot;h=c983ed400dc278dcf20bdff68252fad6d9db7af9;sf=tgz : c78794ccbebe3ca382df66ee517a78eab8921e20044b7d6379d4f3eeea8936bf
license    : AGPL-3.0
summary    : URW+ Postscript core35 fonts
description: |
    URW+ Postscript core35 fonts
install    : |
    mkdir -p $installdir/usr/share/fonts/Type1
    mv $srcdir/* $installdir/usr/share/fonts/Type1/
    rm $installdir/usr/share/fonts/Type1/{COPYING,LICENSE}
