name       : urw-core35-fonts
version    : '20170801'
release    : 2
source     :
    - https://github.com/ArtifexSoftware/urw-base35-fonts/archive/20170801.tar.gz : 38432cf683c39be23646f34107ad025aefd95d0bdc588bb4675c6d775996f2b0
license    : AGPL-3.0
component  : desktop.font
summary    : URW++ Postscript core35 fonts
description: |
    URW++ Core Font Set. These 35 base fonts are provided freely by URW++ company, and are mainly utilized by Ghostscript, or other applications using it.
install    : |
    install -D -m00644 fonts/*.ttf -t $installdir/usr/share/fonts/truetype/urw-core35
    install -D -m00644 fonts/*.otf -t $installdir/usr/share/fonts/opentype/urw-core35
    install -D -m00644 fonts/*.{afm,t1} -t $installdir/usr/share/fonts/Type1
    install -d -m00755 $installdir/usr/share/fonts/conf.d/

    pushd fontconfig
    for cfg in *.conf; do
        install -D -m00644 $cfg $installdir/usr/share/fontconfig/conf.avail/30-$cfg
        ln -s /usr/share/fontconfig/conf.avail/30-$cfg $installdir/usr/share/fonts/conf.d/30-$cfg
    done
    popd

    install -D -m00644 appstream/*.xml -t $installdir/usr/share/metainfo/
